# Mini Project 6 :- ML Feasibility Assessment of Sleep Health and Lifestyle Dataset

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# objective :-
#The objective of Project-6 is to determine whether the selected dataset is suitable for Machine Learning,
#identify the appropriate ML approach, andjustify the feasibility of applying Machine Learning for solving the given problem.

In [3]:
df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

In [4]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
df.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [7]:
df.shape

(374, 13)

In [8]:
df.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [11]:
df["Sleep Disorder"] = df["Sleep Disorder"].fillna("undecidable")

In [12]:
df.isnull().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

In [13]:
# Target variable Sleep Disorder ke labels dekhne ke liye
print(df["Sleep Disorder"].value_counts())

Sleep Disorder
undecidable    219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [14]:
# Unique labels dekhne ke liye

print(df["Sleep Disorder"].unique())

['undecidable' 'Sleep Apnea' 'Insomnia']

# Numerical & Categorical Features

In [15]:
# Numerical columns identify karne ke liye
print("Numerical Columns")
print(df.select_dtypes(include=["int64","float64"]).columns)

# Categorical columns identify karne ke liye
print("\nCategorical Columns")
print(df.select_dtypes(include=["object"]).columns)

Numerical Columns
Index(['Person ID', 'Age', 'Sleep Duration', 'Quality of Sleep',
       'Physical Activity Level', 'Stress Level', 'Heart Rate', 'Daily Steps'],
      dtype='object')

Categorical Columns
Index(['Gender', 'Occupation', 'BMI Category', 'Blood Pressure',
       'Sleep Disorder'],
      dtype='object')

In [16]:
# Blood Pressure ko Systolic aur Diastolic me split kar rahe hain
df[['Systolic', 'Diastolic']] = df['Blood Pressure'].str.split('/', expand=True)

# String ko integer me convert kar rahe hain
df['Systolic'] = df['Systolic'].astype(int)
df['Diastolic'] = df['Diastolic'].astype(int)

# Original Blood Pressure column remove kar rahe hain
df.drop('Blood Pressure', axis=1, inplace=True)

# ML Approach Identification

In [17]:
# Output categories me hai..... None, Insomnia, Sleep Apnea

# Isliye Classification.

In [18]:
# ML approach identify karne ke liye

target = df["Sleep Disorder"]
print("Unique Labels :")
print(target.unique())
print("Suitable ML Approach : Classification")

Unique Labels :
['undecidable' 'Sleep Apnea' 'Insomnia']
Suitable ML Approach : Classification

In [19]:
# Final conclusion print karne ke liye

print("""
==========================================
ML FEASIBILITY ASSESSMENT
==========================================

1. Dataset is structured.
2. Dataset contains sufficient records.
3. Target variable is available.
4. Labels are clearly defined.
5. Missing values are minimal or absent.
6. Features are relevant for prediction.

Conclusion:
Machine Learning is FEASIBLE on this dataset.

Recommended ML Approach:
CLASSIFICATION

Reason:
The target variable 'Sleep Disorder'
contains categorical labels such as
None, Insomnia and Sleep Apnea.
==========================================
""")

==========================================
ML FEASIBILITY ASSESSMENT
==========================================

1. Dataset is structured.
2. Dataset contains sufficient records.
3. Target variable is available.
4. Labels are clearly defined.
5. Missing values are minimal or absent.
6. Features are relevant for prediction.

Conclusion:
Machine Learning is FEASIBLE on this dataset.

Recommended ML Approach:
CLASSIFICATION

Reason:
The target variable 'Sleep Disorder'
contains categorical labels such as
None, Insomnia and Sleep Apnea.
==========================================

# Label Encoding :-

In [20]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Occupation"] = le.fit_transform(df["Occupation"])
df["BMI Category"] = le.fit_transform(df["BMI Category"])
df["Sleep Disorder"] = le.fit_transform(df["Sleep Disorder"])

X = df.drop("Sleep Disorder", axis=1)

Y = df["Sleep Disorder"]

# Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2,random_state=42)

# Decision Tree Classifier :-

In [22]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

# Accuracy :-

In [23]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy :", accuracy_score(Y_test, y_pred))

Accuracy : 0.9066666666666666