# Mini Project 2 :- Employee Salary Data Processing Using Python

In [1]:
import pandas as pd

In [12]:
# Project Objective - Employee salary dataset ko process karna, business rules apply karna, aur meaningful insights generate karna using Python.

In [2]:
df = pd.read_csv("employee_salary_dataset.csv")

In [4]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [5]:
df.shape

(50, 9)

In [7]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Experience_Years',
       'Education_Level', 'Age', 'Gender', 'City', 'Monthly_Salary'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        50 non-null     int64
 1   Name              50 non-null     object
 2   Department        50 non-null     object
 3   Experience_Years  50 non-null     int64
 4   Education_Level   50 non-null     object
 5   Age               50 non-null     int64
 6   Gender            50 non-null     object
 7   City              50 non-null     object
 8   Monthly_Salary    50 non-null     int64
dtypes: int64(4), object(5)
memory usage: 3.6+ KB

In [9]:
df.describe()

       EmployeeID  Experience_Years        Age  Monthly_Salary
count    50.00000         50.000000  50.000000         50.0000
mean     25.50000          9.900000  39.760000      82288.8000
std      14.57738          5.349995  11.539745      33521.4379
min       1.00000          1.000000  22.000000      28420.0000
25%      13.25000          5.250000  28.250000      59424.0000
50%      25.50000         10.000000  43.500000      73890.5000
75%      37.75000         14.750000  49.000000     107219.0000
max      50.00000         19.000000  57.000000     149123.0000

In [10]:
df.isnull().sum()

EmployeeID          0
Name                0
Department          0
Experience_Years    0
Education_Level     0
Age                 0
Gender              0
City                0
Monthly_Salary      0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
# Business Rule 1:
# Employees ko salary ke basis par categories me divide karna.
# Isse pata chalega kaun High Salary, Medium Salary aur Low Salary group me hai.

def salary_category(salary):

    if salary >= 100000:
        return "High Salary"

    elif salary >= 70000:
        return "Medium Salary"

    else:
        return "Low Salary"

# Function ko Monthly_Salary column par apply karke
# ek naya column Salary_Category create kar rahe hain
df["Salary_Category"] = df["Monthly_Salary"].apply(salary_category)


# Salary Category business rule isliye apply kiya gaya taaki
# employees ko salary ranges ke according classify kiya ja sake aur salary distribution ko easily analyze kiya ja sake

In [15]:
# Business Rule 2:
# Employees ko experience ke basis par classify karna.
# Isse pata chalega employee Junior, Mid-Level ya Senior hai.

def experience_level(exp):
    if exp <= 2:
        return "Junior"

    elif exp <= 7:
        return "Mid-Level"

    else:
        return "Senior"

# Function ko Experience_Years column par apply karke
# ek naya column Experience_Level create kar rahe hain
df["Experience_Level"] = df["Experience_Years"].apply(experience_level)


# Experience Level business rule ka purpose employees ko unke experience ke according categorize karna tha,
# jisse organization me Junior, Mid-Level aur Senior workforce ka analysis kiya ja sake."

In [18]:
df.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Salary_Category,Experience_Level
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,High Salary,Senior
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,Medium Salary,Mid-Level
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,Low Salary,Senior
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,Medium Salary,Senior
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,High Salary,Senior

In [22]:
print("Average Salary Of Employee :", df["Monthly_Salary"].mean())

Average Salary Of Employee : 82288.8

In [23]:
# idxmax() -  highest salary wali row ka index find karta hai
# .loc[] -  us row ki complete details retrieve karta hai."

print("Highest Salary Employee :", df.loc[df["Monthly_Salary"].idxmax()])

Highest Salary Employee : EmployeeID                   38
Name                Employee_38
Department           Operations
Experience_Years              9
Education_Level          Master
Age                          23
Gender                     Male
City                     Mumbai
Monthly_Salary           149123
Salary_Category     High Salary
Experience_Level         Senior
Name: 37, dtype: object

In [27]:
# Ye salary distribution ko department basis par show kar rha hai.

print("Hghest salary on the basis of", df.groupby("Department")["Monthly_Salary"].mean())

Hghest salary on the basis of Department
Finance       67261.900000
HR            82945.142857
IT            76520.500000
Marketing     96430.846154
Operations    84239.900000
Name: Monthly_Salary, dtype: float64

In [30]:
# Ye salary distribution ko gender basis par show kar rha h

print("Highest salary on the bais of", df.groupby("Gender")["Monthly_Salary"].mean())

Highest salary on the bais of Gender
Female    87306.185185
Male      76398.826087
Name: Monthly_Salary, dtype: float64

In [31]:
# Top 5 Highest Paid Employees
df.nlargest(5, "Monthly_Salary")

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Salary_Category,Experience_Level
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123,High Salary,Senior
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381,High Salary,Senior
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616,High Salary,Senior
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455,High Salary,Senior
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,High Salary,Senior